srcdir=.
EXEC=../../extractMemorySkeleton

all: test

include Makefile.common

test:
	${MAKE} -f Makefile.manual ${MARKS}
	${MAKE} -f Makefile.manual ${ALL_OBJS}
	${MAKE} -f Makefile.manual ${ALL_EXPECTED:.expected=.comp}

.PHONY: simple
simple:
	$(MAKE) -C simple

clean:
	rm -f ${ALL_OUTS} ${ALL_OBJS} ${MARKS} */*.ti
